const WA='52XXXXXXXXXX'; // número de ASTRA con lada de país
const P={target:'<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',drop:'<path d="M12 2.7l5.7 5.6a8 8 0 1 1-11.4 0z"/>',grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',trend:'<path d="M23 6l-9.5 9.5-5-5L1 18"/><path d="M17 6h6v6"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 0 0-7.8 7.8l1 1.1L12 21l7.8-7.5 1-1.1a5.5 5.5 0 0 0 0-7.8z"/>',send:'<path d="M22 2L11 13M22 2l-7 20-4-9-9-4z"/>',monitor:'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>',box:'<path d="M21 8v13H3V8M1 3h22v5H1zM10 12h4"/>',pulse:'<path d="M22 12h-4l-3 9L9 3l-3 9H2"/>',users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',flag:'<path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1zM4 22v-7"/>',home:'<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zM9 22V12h6v10"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6"/>',cal:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',msg:'<path d="M21 11.5a8.4 8.4 0 0 1-12.5 7.3L3 21l1.9-5.4A8.4 8.4 0 1 1 21 11.5z"/>',clip:'<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1"/>',search:'<circle cx="11" cy="11" r="8"/><path d="M21 21l-4.3-4.3"/>',alert:'<path d="M10.3 3.9L1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0zM12 9v4M12 17h.01"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1"/>'};
const I=n=>`<svg class="i" viewBox="0 0 24 24">${P[n]}</svg>`;
const C={m:['#BDE8E0','#2B8A86'],r:['#FFC9D4','#D9566F'],s:['#BFDDF7','#3C82C2'],p:['#FFE0B8','#C9831C'],l:['#DCCBF2','#7650B8'],g:['#C6EBD6','#3E9E73']};
const cs=k=>`--b:${C[k][0]};--d:${C[k][1]}`;
const D=[['Identidad y estrategia','Propósito, misión, visión, valores, FODA y objetivos','target','m'],['Marca e imagen','Logotipo, paleta, manual de identidad y señalización','drop','r'],['Organización','Organigrama, perfiles, funciones y comunicación','grid','s'],['Procesos y manuales','SOP, políticas, recepción, caja y calidad','list','m'],['Administración y finanzas','Ventas, costos, margen, flujo e indicadores','trend','p'],['Clientes y pacientes','Recurrencia, seguimiento, quejas y fidelización','heart','l'],['Marketing y ventas','Canales, reputación, leads y campañas','send','r'],['Tecnología y datos','Software, expediente, respaldos y seguridad','monitor','s'],['Inventario y compras','Máx/mín, caducidades, rotación y mermas','box','p'],['Operación clínica','Protocolos, receta, consentimiento y continuidad','pulse','g'],['Capital humano','Inducción, capacitación, desempeño e incentivos','users','l'],['Crecimiento y dirección','Capacidad, expansión, precios y riesgos','flag','m']];
const N=['Inexistente','Reactivo / informal','Definido','Implementado','Gestionado'];
const E=['Calificar','Preparar','Levantar','Analizar','Validar','Presentar'],ES=['Sponsor · necesidad · alcance','Formulario · hipótesis · agenda','Entrevista 360° · evidencias','Madurez · hallazgos · prioridad','QA · trazabilidad','Escenario · decisiones · ASTRA 90'];
const F01=[['Contexto','Nombre comercial, ubicación, antigüedad, sucursales, horarios y quién decide.'],['Servicios e ingresos','Servicios principales, mezcla de ventas, ticket promedio y rentabilidad.'],['Equipo','Colaboradores, puestos, turnos, responsables y vacantes críticas.'],['Objetivos','3 objetivos a 12 meses y 3 resultados a mejorar en 90 días.'],['Identidad visual','Logo, paleta, tipografías, manual, fotografías y señalización.'],['Dirección estratégica','Misión, visión, valores, FODA, propuesta de valor y plan anual.'],['Procesos','Procesos documentados, formatos, retrabajo y dependencia de personas.'],['Finanzas y control','Indicadores que revisa dirección: ventas, margen, gastos, flujo y metas.'],['Clientes/pacientes','Registro, recordatorios, seguimiento, reactivación y quejas.'],['Marketing','Redes, web, Google Business, campañas, reputación y métricas.'],['Tecnología','Software actual, módulos usados, expediente, agenda, inventario y respaldos.'],['Inventario/compras','Proveedores, máx/mín, caducidades, rotación y conteos.'],['Capital humano','Perfiles, inducción, capacitación, evaluación y comunicación.'],['Dolores actuales','Los 3 problemas que más afectan control, experiencia o rentabilidad.'],['Éxito esperado','¿Cómo sabrá Dirección, con datos, que ASTRA fue exitoso?']];
const DEL=[['F01','Formulario pre-diagnóstico'],['F02','Mapa 12 dimensiones'],['F03','Evaluación de madurez'],['F04','Checklist de evidencias'],['F05','Diagnóstico vs. evidencia'],['P01','Presentación ejecutiva'],['R90','Roadmap ASTRA 90'],['MIN','Minuta de acuerdos']];
const QA=['Alcance y limitaciones visibles','12 dimensiones revisadas o justificadas N/A','Puntajes 3–4 con evidencia','Hallazgos prioritarios trazables','Cifras y porcentajes recalculados','Recomendaciones viables','Información sensible minimizada','Presentación sin contradicciones','Decisiones requeridas explícitas','Roadmap con responsable, fecha, KPI y cierre'];
const R=[['0–30 días · Control','m',['Línea base','Responsables','Procesos críticos'],'G1 · Línea base aprobada'],['31–60 días · Estandarización','s',['Manuales','Capacitación','Tecnología'],'G2 · Procesos críticos listos'],['61–90 días · Crecimiento','r',['Marketing','Fidelización','Rentabilidad'],'G4 · KPIs antes/después']];
const Q=['¿Conoce su utilidad operativa mensual real?','¿Separa ventas por consulta, farmacia, laboratorio, estética y alimento?','¿Tiene ticket promedio y número de transacciones por mes?','¿Hay proceso formal para citas, confirmaciones y no-show?','¿Los expedientes clínicos están completos y accesibles?','¿Tiene calendario de vacunación/prevención con seguimiento?','¿El inventario tiene mínimos, máximos, lotes y caducidades?','¿Conoce cuánto pierde por merma/caducidad?','¿Cada puesto tiene responsabilidades y métricas?','¿El dueño puede ausentarse un día sin que la operación se detenga?','¿Los tutores reciben seguimiento y recordatorios?','¿Su software genera información que realmente usa para decidir?'];
const $=s=>document.querySelector(s),wa=t=>`https://wa.me/${WA}?text=${encodeURIComponent(t)}`,pad=n=>String(n).padStart(2,0);
const sec=(n,t)=>`<div class="sec"><b>${n}</b><h2>${t}</h2></div>`,head=(c,t,s)=>`<h2 class="t">${c} · ${t}</h2><p class="lead">${s}</p>`;
const V={
panel:['home','Panel',()=>`<header class="hero"><div><em>Tu clínica, nuestra experiencia, su mejor futuro</em><h1>Programa de Crecimiento para Clínicas Veterinarias</h1><div class="pills"><span>Consultoría</span><span>Software</span><span>Capacitación</span><span>Resultados</span></div></div><img src="img/logo-astra.png" alt=""></header>
<div class="badges">${[['Más ventas','Incrementa tu rentabilidad','trend','g'],['Control operativo','Procesos claros','gear','r'],['Software todo en uno','Expedientes, citas, recetas','monitor','s'],['Equipo capacitado','Mejor atención','users','p'],['Clientes felices','Fidelización','heart','l']].map(b=>`<div class="badge"><i style="${cs(b[3])}">${I(b[2])}</i><b>${b[0]}</b><small>${b[1]}</small></div>`).join('')}</div>
${sec(1,'Ruta del diagnóstico 360°')}<div class="flow">${E.map((e,i)=>`<div style="${cs('msprlg'[i])}"><b>${i+1}</b><strong>${e}</strong><br><small>${ES[i]}</small></div>`).join('')}</div>
${sec(2,'Las 12 dimensiones ASTRA')}<div class="dims">${D.map((d,i)=>`<article style="${cs(d[3])}"><h3><span class="ico">${I(d[2])}</span>${pad(i+1)} ${d[0]}</h3><p>${d[1]}</p></article>`).join('')}</div>
${sec(3,'Entregables del expediente')}<div class="bar"><i id="pb"></i></div><div class="deliv">${DEL.map(d=>`<label><input type="checkbox" hidden><code>${d[0]}</code>${d[1]}</label>`).join('')}</div>`],
score:['clip','Scorecard',()=>`${head('Lead magnet','¿Dónde se fuga la rentabilidad de tu clínica?','12 preguntas · Sí = 2, Parcial = 1, No = 0')}<form id="f">${Q.map((q,i)=>`<fieldset class="card"><b>${i+1}. ${q}</b><br>${[[2,'Sí'],[1,'Parcial'],[0,'No']].map(o=>`<label class="opt"><input type="radio" name="q${i}" value="${o[0]}" required><span>${o[1]}</span></label>`).join('')}</fieldset>`).join('')}<button class="btn big">Ver mi semáforo</button></form><div id="res"></div>`],
f01:['file','F01 Pre-diagnóstico',()=>`${head('ASTRA-F01','Formulario pre-diagnóstico','15 preguntas clave. El cliente responde antes de la entrevista.')}${F01.map((q,i)=>`<details class="q" style="${cs('msprlg'[i%6])}"><summary><span class="ico" style="width:34px;height:34px">${pad(i+1)}</span>${q[0]}</summary><p class="lead">${q[1]}</p><textarea></textarea></details>`).join('')}`],
f03:['search','F03 Madurez',()=>`${head('ASTRA-F03','Evaluación digital de madurez','Puntaje 0–4 por dimensión, con evidencia y decisión.')}<section class="score"><div class="ring" id="ring"><b id="pct">0%</b></div><div><h2 id="pts">0 / 48 puntos</h2><p id="fort">Fortalezas: —</p><p id="brec">Brechas: —</p></div></section><div id="dl">${D.map((d,i)=>`<details class="dim" style="${cs(d[3])}"><summary><span class="ico">${I(d[2])}</span>${pad(i+1)} ${d[0]}<span class="pill" id="p${i}">Nivel 0 · ${N[0]}</span></summary><div class="lv">${N.map((n,k)=>`<label><input type="radio" name="d${i}" value="${k}" ${k?'':'checked'}><span>${k}<small>${n}</small></span></label>`).join('')}</div><textarea placeholder="Evidencia y hallazgo"></textarea></details>`).join('')}</div>`],
f04:['list','F04 Evidencias',()=>`${head('ASTRA-F04','Checklist de evidencias','D disponible · P parcial · NE no existe · N/A no aplica · PD pendiente')}${D.map((d,i)=>`<div class="card row" style="${cs(d[3])}"><b><span class="ico">${I(d[2])}</span></b><strong>${d[0]}</strong><select>${['D','P','NE','N/A','PD'].map(s=>`<option>${s}</option>`)}</select><input type="text" placeholder="Fuente y fecha"></div>`).join('')}`],
f05:['alert','F05 Hallazgo',()=>`${head('ASTRA-F05','Diagnóstico vs. evidencia','Una ficha por hallazgo, explicable en menos de 90 segundos.')}<div class="card">${['Situación actual','Evidencia observada','Brecha','Causa probable','Impacto','Recomendación ASTRA','KPI','Meta / criterio de cierre'].map(c=>`<label>${c}<textarea></textarea></label>`).join('')}<label>Dimensión<select>${D.map(d=>`<option>${d[0]}</option>`)}</select></label><label>Riesgo<select><option>Bajo<option>Medio<option>Alto<option>Crítico</select></label><label>Prioridad<select><option>Ahora<option>30 d<option>60 d<option>90 d</select></label></div>`],
r90:['cal','Roadmap ASTRA 90',()=>`${head('R90','Roadmap ASTRA 90','De diagnóstico a ejecución en 12 semanas.')}<div class="fase">${R.map(f=>`<section style="${cs(f[1])}"><h3>${f[0]}</h3><ul>${f[2].map(x=>`<li>${I('target')} ${x}</li>`).join('')}</ul><span class="gate">${f[3]}</span></section>`).join('')}</div>${sec('QA','Control de calidad antes de presentar')}<div class="deliv">${QA.map(q=>`<label><input type="checkbox" hidden><code>${I('target')}</code>${q}</label>`).join('')}</div>`]};
$('#nav').innerHTML=Object.entries(V).map(([k,v])=>`<a data-v="${k}">${I(v[0])}${v[1]}</a>`).join('');
$('#wa').innerHTML=I('msg')+' Agenda tu diagnóstico';$('#wa').href=wa('Hola, quiero agendar mi diagnóstico gratuito de 30 minutos con ASTRA.');
function go(k){$('#m').innerHTML=V[k][2]();document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('on',a.dataset.v===k));scrollTo(0,0);
 if(k==='f03'){const lv=D.map(()=>0);$('#dl').onchange=e=>{const i=+e.target.name.slice(1),v=+e.target.value;lv[i]=v;$('#p'+i).textContent=`Nivel ${v} · ${N[v]}`;const t=lv.reduce((a,b)=>a+b),o=lv.map((_,i)=>i).sort((a,b)=>lv[b]-lv[a]),n=a=>a.map(i=>D[i][0]).join(', '),pc=Math.round(t/.48);$('#pts').textContent=`${t} / 48 puntos`;$('#pct').textContent=pc+'%';$('#ring').style.setProperty('--p',pc);$('#fort').textContent='Fortalezas: '+n(o.slice(0,3));$('#brec').textContent='Brechas: '+n(o.slice(-3).reverse())}}
 if(k==='score')$('#f').onsubmit=e=>{e.preventDefault();const p=[...new FormData(e.target).values()].reduce((a,b)=>a+ +b,0),s=p<=8?['Urgencia operativa','r']:p<=16?['Control parcial','p']:['Base sólida con oportunidades','g'];$('#res').innerHTML=`<section class="card" style="${cs(s[1])};text-align:center;border-top:10px solid var(--d)"><h2>${p} / 24 · ${s[0]}</h2><p>El puntaje orienta la conversación; no sustituye el diagnóstico.</p><a class="btn" style="background:#3E9E73;box-shadow:0 5px 0 #2b7453" target="_blank" rel="noopener" href="${wa(`Hola, hice el Scorecard ASTRA (${p}/24) y quiero agendar mi diagnóstico.`)}">Agenda tu diagnóstico gratuito</a></section>`;$('#res').scrollIntoView({behavior:'smooth'})};
 const bar=()=>{const c=[...document.querySelectorAll('.deliv input')];if(k==='panel'&&$('#pb'))$('#pb').style.width=c.filter(x=>x.checked).length/c.length*100+'%'};document.querySelectorAll('.deliv input').forEach(x=>x.onchange=bar)}
$('#nav').onclick=e=>{const a=e.target.closest('a');a&&go(a.dataset.v)};go('panel');